microprofile/microprofile-jwt-auth

.gitignore, LICENSE, README.adoc, api/pom.xml, pom.xml, spec/pom.xml, spec/src/main/asciidoc/background.asciidoc, spec/src/main/asciidoc/interoperability.asciidoc, spec/src/main/asciidoc/license-alv2.asciidoc, spec/src/main/asciidoc/microprofile-jwt-auth-spec.asciidoc, tck/pom.xml, tck/running_the_tck.asciidoc
Signed-off-by: Scott Stark <starksm64@gmail.com>
=> Switch to ASLv2 license

api/pom.xml
This addresses #18 
Signed-off-by: Scott M Stark <starksm64@gmail.com>
=> include the source jar in the api build

api/bnd.bnd, api/pom.xml, api/src/main/java/org/eclipse/microprofile/auth/package-info.java, api/src/main/java/org/eclipse/microprofile/jwt/package-info.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/JsonValuejectionEndpoint.java
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
=> #30 bundlise the artifact

pom.xml
Signed-off-by: Scott Stark <starksm64@gmail.com>
=> Change developerConnection to use ssh style of uri

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/JsonValuejectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ProviderInjectionEndpoint.java
I haven't created a ticket for this one as it's only small formatting, but I'm happy to do it if you wish
=> Make messages readable for end user

tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/ITokenParser.java, tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/TokenUtils.java
I haven't created a ticket for this one as it's only small formatting, but I'm happy to do it if you wish
=> javadoc, token utils cleanup

tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/IssNoValidationBadIssTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/IssNoValidationNoIssTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/IssValidationFailTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/IssValidationTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyAsFileLocationURLTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyAsJWKLocationTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyAsPEMLocationTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyAsPEMTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/JsonValueInjectionTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrincipalInjectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrincipalInjectionTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RequiredClaimsTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/UnsecuredPingTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsTest.java
Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>
=> JWT Auth TCK improvement

spec/src/main/asciidoc/background.asciidoc, spec/src/main/asciidoc/configuration.asciidoc, spec/src/main/asciidoc/future-directions.asciidoc, spec/src/main/asciidoc/interoperability.asciidoc
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
=> Small fixes in the spec documentation.

api/pom.xml
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
Fixes #146
=> #146 add bnd baseline plugin to version packages

api/pom.xml, api/src/main/java/org/eclipse/microprofile/auth/LoginConfig.java, api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java
=> Fix JavaDoc warnings and make the osgi dependency provided

api/pom.xml, pom.xml, tck/pom.xml
=> Update to MP 3.3 Jakarta dependencies

api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java
=> Add methods to JsonWebToken to get claims by using the Claims enum

api/pom.xml, tck/pom.xml
=> Exclude el API dependency

README.adoc, tck/README.adoc
=> Fix Readme

api/src/main/java/org/eclipse/microprofile/jwt/config/Names.java, spec/src/main/asciidoc/configuration.asciidoc, tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/MpJwtTestVersion.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudArrayValidationTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudValidationBadAudTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudValidationMissingAudTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudValidationTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudienceValidationEndpoint.java, tck/src/test/resources/TokenAudiences.json, tck/src/test/resources/suites/tck-base-suite.xml
Signed-off-by: Bruce Tiffany <btiffany@us.ibm.com>
=> add mp.jwt.verify.audiences requirements and tests

spec/src/main/asciidoc/interoperability.asciidoc, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionEndpoint.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsTest.java, tck/src/test/resources/Token1.json
=> Support injection for long and boolean primitive types.

spec/src/main/asciidoc/release-notes.asciidoc
This PR add MP JWT 1.2 Release notes following the format used by MP Config, OpenApi etc.
I'll appreciate a quick review as I'd like to do the `RC1` release asap
CC @Emily-Jiang
=> Add MP JWT 1.2 Release notes

api/pom.xml
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
=> 203 - put the baseline to the last final release

tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/TokenAsCookieIgnoredTest.java, tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/TokenAsCookieTest.java
Signed-off-by: Adam Yoho <ayoho@us.ibm.com>
=> Update MP Config comment in TokenAsCookieTest and TokenAsCookieIgnoredTest

spec/src/main/asciidoc/release-notes.asciidoc
This is a minor update to the Release Notes as requested by @ederks85.
(similarly to the MP Config release notes)
=> Update the release notes with a link to the Jakarta API update PR

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
This reverts commit 831c62afc932eba17d6a0c442b958552c99199ac.
=> Revert "[maven-release-plugin] prepare release"

.github/workflows/build.yml
Hi @starksm64, @radcortez  as per your discussion
=> Update the build workflow to setup java at v1

README.adoc, api/src/main/java/org/eclipse/microprofile/jwt/package-info.java, spec/src/main/asciidoc/background.asciidoc
- Updated README.adoc
- Updated Specs background
- Updated Javadocs package-info
Signed-off-by: Emerson Castaneda <emecas@users.noreply.github.com>
=> Fixing RBAC Capitalization and Minor Typos for JWT & OIDC in Different Places

spec/src/main/asciidoc/interoperability.asciidoc
Fix package and import of LoginConfig
=> Minor specification fixes

pom.xml
=> Bump TCK jose4j version to 0.7.9

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
Updating the master so that it can be easier to eventually merge to it from `jakarta91-branch`
=> Update the version to to 2.0.0-SNAPSHOT

tck/pom.xml
=> Build TCK Tests JAR

.gitignore, tck/pom.xml
Fixes: #261 (additional fixes)
=> add javadoc and source for test-jar

NOTICE, api/src/main/META-INF/LICENSE, api/src/main/META-INF/NOTICE, pom.xml, spec/src/main/META-INF/LICENSE, spec/src/main/META-INF/NOTICE, tck/src/main/resources/META-INF/LICENSE, tck/src/main/resources/META-INF/NOTICE
=> Add LICENSE and NOTICE resources to all modules

pom.xml
The build will fail as MP Config is not in Central yet
=> Bump MP Config version to 3.0

pom.xml, spec/src/main/asciidoc/license-efsl.adoc, tck/pom.xml
=> Fix issues for 2.0 Release, test jar, sources and javadoc

spec/src/main/asciidoc/interoperability.asciidoc
=> Replace remaining Java EE references in the spec with Jakarta EE

spec/src/main/asciidoc/release-notes.asciidoc
Updating the notes before 2.1.RC2
=> Update the release notes to mention mp.jwt.decrypt.key.algorithm property

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/TokenAgeTest.java, tck/src/test/resources/META-INF/microprofile-config-verify-token-age.properties, tck/src/test/resources/suites/tck-base-suite.xml, tck/src/test/resources/suites/tck-full-suite.xml
Signed-off-by: Teddy J. Torres <teddyjtorres@hotmail.com>
Adds TokenAgeTest for testing mp.jwt.verify.token.age and update the base and full suites.
=> Refactor tests for mp.jwt.verify.token.age into their own class and update suites

api/bnd.bnd
=> Update bnd.bnd to allow this bundle manifest to work with EE 10

tck/src/test/resources/suites/tck-base-suite.xml, tck/src/test/resources/suites/tck-build-suite.xml, tck/src/test/resources/suites/tck-full-suite.xml
=> Remove DTO declarations from TCK test suite files
