microprofile/microprofile-jwt-auth

api/src/main/java/org/eclipse/microprofile/jwt/Claim.java
pom.xml
spec/src/main/asciidoc/interoperability.asciidoc
spec/src/main/asciidoc/microprofile-jwt-auth-spec.asciidoc
tck/pom.xml
tck/running_the_tck.asciidoc
tck/src/test/java/org/eclipse/microprofile/jwt/tck/TCKConstants.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/ejb/EjbEndpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/ejb/EjbTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/ejb/IService.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/ejb/ServiceEJB.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jacc/SubjectEndpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jacc/SubjectTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesEndpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/servlet/ServiceServlet.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/servlet/ServletTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/parsing/TokenValidationTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsTest.java
tck/tck-base-suite.xml
tck/tck-full-suite.xml
tck/tck-null-suite.xml

* Switch to TestNG 
* Classify tests by groups to allow for base and optional tests
* Expand the base required tests 
* Add optional tests 
* update the spec and tck docs
* Document how to run the TCK from within an implementation's TCK harness build

TCK and documentation updates

---

api/src/main/java/org/eclipse/microprofile/jwt/Claim.java

Make claim attributes nonbinding to allow producers.
This closes #28
This closes #32

Allow claim to target types (for non-portable behavior).

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionEndpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionTest.java

Tests to assert support detailed in specification for injecting claims as their primitive types into `@RequestScoped` beans
From Section 7.1.2
```
@Path("/endp")
@RequestScoped
public class RolesEndpoint {
...
// Raw types
@Inject
@Claim(standard = Claims.raw_token)
private String rawToken;
@Inject ①
@Claim(standard=Claims.iat)
private Long issuedAt;
```

Primitive injection of claims for @RequestScoped beans

---

api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java

Reverts eclipse/microprofile-jwt-auth#155 due to this build failure:
https://ci.eclipse.org/microprofile/job/JWT-Auth-maven-snapshots/1063/
```
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-baseline-maven-plugin:3.5.0:baseline (baseline) on project microprofile-jwt-auth-api: An error occurred while calculating the baseline: The baselining plugin detected versioning errors -> [Help 1]
```

Revert "Add methods to JsonWebToken to get claims by using the Claims enum"

---

api/pom.xml
api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java
api/src/main/java/org/eclipse/microprofile/jwt/package-info.java

As discussed in #154 as well as #155 and #156.
This PR adds a default method to retrieve claims with the `Claims` enum. Furthermore, following the discussions mentioned above, the bnd plugin version is increased and the osgi package version of the jwt package is increased to 1.1.
fixes #154

Add get claims with claims, update bnd plugin version and increase jwt package osgi version to 1.1

---

tck/README.adoc
tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyAsPEMTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/InvalidTokenTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/JsonValueInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrimitiveInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/PrincipalInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ProviderInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RequiredClaimsTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java
tck/src/test/resources/META-INF/microprofile-config-publickey-location.properties

This PR completes the #164 PR.
Fixes #135

Fix All JAXRS TCK tests and update the licence year for the affected tests

---

.github/workflows/build.yml
pom.xml

We could move to Github Actions to handle Build and Release process for MicroProfile Config. Some of the main motivations to move are:
- Run the build in forks. You don't need to do the PR to check the status of the build
- Change the Build / Release configuration by just submitting a PR
- Committers have control over the CI
- Flexible to execute actions on Github Events
I've detailed some of the work done over SmallRye to use Github Actions here:
https://github.com/smallrye/smallrye-parent/wiki/SmallRye-Release-Process
The idea is not to pull the plug on Jenkins yet. We can run both in parallel. We can start with just the build part, which is easy to implement and go from there.

Added Github Action Workflow for Build.

---

spec/src/main/asciidoc/configuration.asciidoc
spec/src/main/asciidoc/interoperability.asciidoc
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesEndpoint.java
tck/src/test/resources/TokenNoGroups.json

This PR updates `interoperability` document and adds a simple test (`PermitAll` is really equivalent to requiring no RBAC).
Fixes #129.
CC @radcortez, Roberto, not sure why I can't request a review from you, probably need to update some permissions

Make groups claim optional

---

spec/src/main/asciidoc/interoperability.asciidoc

Fixes #183.
I've restored the bit related to DeploymentException and SessionScoped beans with some minor restructuring. Also dropped some old note, there is no much point to keep it just to keep promising the exp grace may be added, we can add it anyway. 
CC @radcortez 
Given the update I do think we'd be better off with just dropping a `SessionScoped` baggage, a warning is good enough. If it works for some other bigger scopes whatever they are (where NPE etc may also happen) then it works for SessionScoped. 
Thoughts ?

Clarify how a claim value injection is handled for SessionScoped beans

---

spec/src/main/asciidoc/configuration.asciidoc
tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/TokenUtils.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RsaKeySignatureTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsTest.java
tck/src/test/resources/META-INF/microprofile-config-rsakey1024-location.properties
tck/src/test/resources/rsaPrivateKey1024bit.jwk
tck/src/test/resources/rsaPublicKey1024bit.jwk
tck/src/test/resources/suites/tck-base-suite.xml

Fixes #197
A simple test has been added to verify that a token signed with the 1024 bit length RSA key is accepted, it reuses the `RolesAllowed` endpoint
CC @darranl, @teddyjtorres

Add a TCK test for RSA keys of 1024 bit key length

---

spec/src/main/asciidoc/configuration.asciidoc

Fix minor typo in the mp.jwt.decrypt.key.location description.

Fix mp.jwt.decrypt.key.location description

---

pom.xml

This is related to #200 and is likely a reason behind a https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/401/console failure, so I'll get ahead with the merge immediately

Add GPG plugin configuration

---

api/src/main/java/org/eclipse/microprofile/auth/LoginConfig.java

Related #182 
This PR is the first step in the long (possibly never ending) process of dropping `LoginConfig`:
- removes the references to all but `MP-JWT` methods - `MP-JWT` spec should really be only about JWT; note dropping these references from the doc only serves this purpose, i.e, stop sending the message that `LoginConfig` can be an annotation for all sort of auth mechanisms
- `MP-JWT` is a default method now - it does not break the backward compatibility since until now setting the auth method is required, I suspect in the vast majority of cases where this annotation is still used it is `@LoginConfig(authMethod="MP-JWT")` so at least the users will now be able to do just `@LoginConfig`...
- updated the baseline version in this package to `1.1` - I'm scared of this update the most …

LoginConfig: remove refs to all but the MP-JWT method and make MP-JWT the default one

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RequiredClaimsEndpoint.java

Resolves #209
Adds the `/verifyTokenWithoutName` endpoint to the `RequiredClaimsEndpoint` class to avoid encountering a 404 by the test.
Signed-off-by: Adam Yoho <ayoho@us.ibm.com>

Issue 209: Add missing verifyTokenWithoutName endpoint

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/ECPublicKeyAsPEMTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ApplicationScopedInjectionTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/AudArrayValidationTest.java

Updates a few TCK test classes to ensure the WAR file generated for the test application is consistent with the test class name.
Signed-off-by: Adam Yoho <ayoho@us.ibm.com>

Update WAR file names for TCK tests

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/EmptyTokenTest.java

The tests in the `EmptyTokenTest` class are configured to accept `text/plain` as the response from the test endpoint, however the test endpoint is returning a JSON response.
Signed-off-by: Adam Yoho <ayoho@us.ibm.com>

Fix media type accepted by EmptyTokenTest tests

---

tck/pom.xml

Hi Roberto, this is a minor update, given that you spotted 1.3 was too old; other versions can be considered but for now this is a safe update :-)

Update TCK to depend on MP Config 1.4

---

.github/workflows/build.yml
spec/pom.xml

Signed-off-by: Scott M Stark <starksm64@gmail.com>
Addresses the issue I mentioned at https://groups.google.com/u/1/g/microprofile/c/T_XcmTbQp6Q where the
staged org.eclipse.microprofile.jwt:microprofile-jwt-auth-spec artifact is missing the html/pdf spec contents.

Add the build-helper-maven-plugin to attach spec artifacts

---

spec/pom.xml

Running an install did not work. This fixes the problem with the config.spec.pdf/config.spec.html settings.
Signed-off-by: Scott M Stark <starksm64@gmail.com>

Correct the config.spec.* variables to not include the version.

---

api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java
spec/src/main/asciidoc/interoperability.asciidoc

Fixes #234.
Fixes #235.
@keilw has reported these 2 issues and this PR fixes them. I don't think it requires a `1.2.1` maintenance release, these are the obvious and old typo/text bugs, no-one has noticed it during the last few years, so I'd not make a big deal out of it - it will be in the next platform release anyway. That said, I don't mind much doing a `1.2.1` tag.

Minor JavaDoc and specification fixes

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/ApplicationScopedInjectionTest.java

This test is poking the wrong endpoint, essentially just rerunning one of the other tests.
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>

Fix ApplicationScopedInjectionTest#verifyInjectedRawTokenJwt Test

---

tck/src/test/resources/suites/tck-full-suite.xml

It appears the full-suite xml has fallen behind the base-suite and runs substantially fewer tests.

Add Tests Ran in Base Suite to Full Suite

---

spec/src/main/asciidoc/configuration.asciidoc
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/InvalidTokenTest.java
tck/src/test/resources/META-INF/microprofile-config-publickey-location.properties

Signed-off-by: Teddy J. Torres <teddyjtorres@hotmail.com>
For issue #195

Create mp.jwt.verify.token.age config property for issue #195

---

spec/src/main/asciidoc/configuration.asciidoc

Do not set a default mp.jwt.verify.clock.skew value

---

spec/src/main/asciidoc/configuration.asciidoc

The `publickey.location` section needs to be followed by these subsections to specify how people can supply the value of `publickey.location`.
- Relative Path
- `file:` URL Scheme
- `http:` URL Scheme
- Other URL Schemes

Move publickey.algorithm section

---

spec/src/main/asciidoc/configuration.asciidoc
tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/KeyManagementAlgorithm.java
tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/TokenUtils.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe/RolesAllowedSignEncryptRsaOaep256Test.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe/RolesAllowedSignEncryptTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsEncryptTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/util/TokenUtilsSignEncryptTest.java
tck/src/test/resources/META-INF/microprofile-config-verify-decrypt-rsa-oaep-256.properties
tck/src/test/resources/suites/tck-base-suite.xml

Fixes #289.
See #289 for all the details and specifically [this comment](https://github.com/eclipse/microprofile-jwt-auth/issues/289#issuecomment-1122205115).
In summary, an `mp.jwt.decrypt.key.algorithm` is introduced to prepare a transition to `RSA-OAEP-256` becoming a default algorithm used to decrypt the content encryption key. `RSA-OAEP` remains a default algorithm in 2.1. `RSA-OAEP-256` will become a new default in the next major release. `mp.jwt.decrypt.key.algorithm` might become a list property too.
CC @teddyjtorres @rdebusscher

Add support for RSA-OAEP-256 key management algorithm

---

tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/TokenUtils.java

Fixes #295 
There are two possible solutions and I decided to do both :smiley:.
* The AES key is generated setting the key size and not using default (256 was chosen).
* The algorithm selection is done using the bits of the secret key (length in bytes * 8).
If you prefer any other solution just let me know.
Thanks in advance!

Issue #295: TokenUtilsEncryptTest is failing on OpenJDK 19 EA

---

tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe/RolesAllowedSignEncryptRsaOaepTest.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe/RolesAllowedSignEncryptTest.java
tck/src/test/resources/META-INF/microprofile-config-verify-decrypt-rsa-oaep.properties
tck/src/test/resources/suites/tck-base-suite.xml

CC @dblevins @teddyjtorres @rdebusscher 
As agreed in #298, the negative `RSA-OAEP-256` test has been updated to pass only if `mp.jwt.decrypt.key.algorithm=RSA-OAEP` is set.
Please review/approve asap, I'd like to release `RC4` tomorrow evening and then we can do the final one soon afterwards

Add RolesAllowedSignEncryptRsaOaepTest and move negative RSA-OAEP-256 test to it from RolesAllowedSignEncryptTest

---

spec/src/main/asciidoc/configuration.asciidoc
spec/src/main/asciidoc/interoperability.asciidoc

This PR updates `interoperability.doc` to get it synced with the changes made in #292 and #306 since now both `RSA-OAEP` and `RSA-256-256` are formally supported.
@dblevins @rdebusscher @teddyjtorres @Emily-Jiang , please approve and it will be totally ready for the final IMHO, another RC won't be needed for this change.

Fixing interoperability.doc to clarify both RSA-OAEP and RSA-OAEP-256 have to be supported

---

api/src/main/java/org/eclipse/microprofile/jwt/JsonWebToken.java

My colleague spotted the problem, `preferred_username` is not unique, while JsonWebToken#getName talks about uniqueness.
This PR gently warns users that if they really need a unique principal identifier they should get a subject claim.
Ideally we'd remove any explicit mentioning of preferred_username - but it is hard to do right without possibly breaking a lot of user applications. May be in some basic cases it can be unique,  but definitely not in the OIDC space
CC @ayoho

Recommend getting the sub claim to guarantee uniqueness in the JsonWebToken.getName JavaDocs

---

spec/src/main/asciidoc/configuration.asciidoc
tck/src/main/java/org/eclipse/microprofile/jwt/tck/util/MpJwtTestVersion.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/PublicKeyEndpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/RS256OrES256Endpoint.java
tck/src/test/java/org/eclipse/microprofile/jwt/tck/config/RsaAndEcSignatureAlgorithmTest.java
tck/src/test/resources/META-INF/microprofile-config-rsa-ec.properties
tck/src/test/resources/rs256es256.jwk
tck/src/test/resources/suites/tck-base-suite.xml
tck/src/test/resources/suites/tck-full-suite.xml

This PR is meant to align a situation with a non configured signature algorithm is managed with how it is done for the unconfigured decryption algorithm.
If a decryption algorithm is not configured, both `RSA-OAEP` and `RSA-OAEP-256` encryped tokens must be accepted.
Now, similarly, if a signature algorithm is not configured, both `RS256` and `ES256` signed tokens must be accepted.
The end goal is to let an MP JWT Bridge [JwtAuthenticationMechanismDefinition](https://github.com/eclipse/microprofile-jwt-bridge/blob/main/api/src/main/java/org/eclipse/microprofile/jwt/bridge/authentication/mechanism/JwtAuthenticationMechanismDefinition.java) offer a consistent List representation for both signature and encryption properties
CC @ayoho @jimmy1wu

Require that both RS256 and ES256 must be supported if the signature algorithm is not configured
